export const A1_A2 = [
  "apple", "artist", "baby", "back", "ball", "banana", "bathroom", "beach", "bedroom", "beginning", 
  "bird", "birthday", "book", "bottle", "bread", "breakfast", "brother", "building", "bus", "butter", 
  "cafe", "camera", "carpet", "castle", "cat", "ceiling", "cheese", "chicken", "children", "chocolate", 
  "church", "city", "classroom", "clock", "cloud", "coffee", "color", "computer", "concert", "country", 
  "cousin", "cupboard", "dancing", "daughter", "day", "dentist", "desk", "dinner", "doctor", "dog", 
  "door", "dream", "driver", "dress", "duck", "earth", "egg", "elephant", "evening", "eye", "family", 
  "farm", "farmer", "father", "fish", "flower", "food", "forest", "friend", "fruit", "game", "garden", 
  "girl", "glass", "goal", "grandfather", "grandmother", "grass", "ground", "guitar", "hand", "hat", 
  "head", "health", "heart", "home", "homework", "horse", "hospital", "hour", "house", "ice", "idea", 
  "information", "island", "jacket", "job", "juice", "kitchen", "lake", "lamp", "language", "leaf", 
  "library", "life", "light", "lion", "love", "lunch", "magazine", "market", "meat", "medicine", 
  "meeting", "milk", "minute", "mirror", "money", "month", "morning", "mother", "mountain", "mouth", 
  "movie", "music", "name", "neck", "neighbor", "night", "noise", "number", "ocean", "office", "orange", 
  "painter", "paper", "park", "party", "pen", "person", "phone", "picture", "pie", "pizza", "place", 
  "plant", "plate", "playground", "police", "postcard", "potato", "present", "price", "printer", 
  "problem", "rain", "recipe", "restaurant", "ring", "river", "road", "room", "salt", "sand", "school", 
  "science", "season", "second", "sheep", "shirt", "shoe", "shop", "shopping", "singer", "sister", 
  "sky", "sleep", "snow", "soccer", "soap", "song", "spoon", "spring", "star", "station", "story", 
  "student", "sugar", "summer", "sun", "table", "teacher", "television", "tent", "thing", "ticket", 
  "time", "toilet", "tomato", "town", "toy", "tree", "truck", "uncle", "village", "voice", "water", 
  "weather", "week", "window", "winter", "world", "year", "yesterday", "zoo", "actor", "animal", 
  "apartment", "art", "baby", "bag", "balloon", "bath", "bed", "bike", "bottle", "bread", "bus", 
  "cake", "car", "cartoon", "cat", "child", "class", "clothes", "cookie", "day", "dish", "doctor", 
  "doll", "duck", "eye", "face", "farm", "fire", "food", "garden", "gift", "glass", "goal", "guitar", 
  "hall", "hat", "head", "heart", "ice", "jungle", "key", "kitchen", "lake", "leaf", "list", "love", 
  "meal", "milk", "money", "moon", "movie", "park", "plant", "rain", "rest", "ride", "room", "rose", 
  "salt", "seat", "shirt", "shoe", "sign", "smile", "snake", "snow", "soap", "spoon", "stone", 
  "table", "thing", "time", "tool", "toy", "town", "tree", "trip", "voice", "week", "wish", "yard", 
  "action", "actor", "adult", "alarm", "anger", "angle", "ankle", "apple", "argue", "artist", "aspect", 
  "attack", "avenue", "baby", "badge", "bag", "ball", "band", "base", "bath", "bed", "bell", "bet", 
  "bike", "bird", "bite", "blade", "blame", "blank", "blog", "boat", "body", "bomb", "bond", "book", 
  "boot", "boss", "bowl", "boy", "brain", "brake", "bread", "bunch", "burn", "bush", "cable", "cake", 
  "call", "camp", "canal", "cap", "card", "cart", "case", "cash", "cat", "cell", "chain", "chair", 
  "chat", "cheek", "chef", "chest", "chip", "city", "clay", "club", "coat", "coin", "cold", "colony", 
  "color", "comb", "comic", "cook", "copy", "cord", "corn", "cost", "cotton", "cover", "crash", "crew", 
  "crowd", "crown", "cup", "curve", "cut", "cycle", "daddy", "dance", "dark", "date", "deal", "debt", 
  "desk", "dial", "diet", "dirt", "disk", "dog", "door", "dot", "dream", "dress", "drum", "dust", 
  "duty", "edge", "egg", "end", "exam", "eye", "face", "fact", "fan", "farm", "fear", "feast", "fee", 
  "feet", "field", "film", "firm", "fish", "flag", "floor", "fly", "food", "fool", "fork", "form", 
  "fowl", "fuel", "fun", "fund", "gang", "gas", "gate", "gift", "goal", "god", "gold", "golf", "good", 
  "grade", "grain", "grass", "grid", "guilt", "hair", "hall", "hand", "hat", "head", "heat", "hill", 
  "hire", "hold", "hole", "hook", "hope", "hour", "ice", "idea", "item", "jack", "jazz", "job", "join", 
  "joy", "judge", "jump", "key", "kid", "kit", "lab", "lady", "lake", "lamp", "land", "law", "leaf", 
  "leg", "lid", "life", "light", "link", "lion", "lip", "load", "lock", "log", "look", "loss", "love", 
  "luck", "mail", "map", "mask", "mate", "meat", "meal", "menu", "mile", "milk", "mind", "mist", 
  "mode", "mood", "moon", "move", "name", "nap", "need", "news", "note", "nut", "oil", "open", "orb", 
  "ore", "page", "pain", "pair", "pan", "park", "path", "peck", "pen", "pet", "pie", "pill", "pin", 
  "pipe", "plan", "play", "plot", "plum", "plus", "pole", "pool", "post", "puck", "push", "quiz", 
  "rail", "rate", "ray", "rent", "rice", "ride", "ring", "risk", "road", "rock", "roof", "rope", 
  "rule", "rush", "sale", "sand", "save", "seed", "set", "ship", "shoe", "shop", "side", "sign", 
  "sink", "sip", "site", "size", "snow", "sock", "song", "sort", "spin", "spot", "star", "stem", 
  "step", "stop", "sum", "swim", "tab", "task", "tax", "team", "tent", "test", "text", "tile", 
  "time", "tip", "tone", "top", "tour", "town", "tray", "tree", "trip", "unit", "use", "vote", 
  "wall", "war", "wax", "week", "wish", "wood", "word", "work", "yard", "year", "zone", "actor", "advice", "afternoon", "agency", "agreement", "alarm", "album", "angle", "area", "army", 
  "author", "aunt", "autumn", "backyard", "balance", "bank", "baseball", "basement", "battle", "beard",
  "bee", "beef", "beginning", "bell", "belt", "bicycle", "bin", "birthday", "blanket", "blood", 
  "blouse", "boat", "bone", "boot", "bowl", "box", "branch", "bread", "break", "bridge", "broccoli", 
  "broom", "brush", "bug", "bun", "bus", "button", "cabinet", "cable", "cage", "candle", "canvas", 
  "carrot", "castle", "ceiling", "chain", "chalk", "champion", "cheese", "chemist", "cherry", "chest", 
  "chewing", "choice", "circle", "classmate", "clay", "clerk", "clinic", "closet", "clown", "coin", 
  "college", "comedy", "comic", "common", "concert", "contest", "control", "copper", "corner", "cost", 
  "cousin", "cream", "creature", "crowd", "crown", "cup", "customer", "cut", "dance", "dancer", "dart", 
  "debt", "deer", "degree", "desk", "detective", "diet", "dinner", "dish", "dive", "dock", "doctor", 
  "doll", "dolphin", "donkey", "drawer", "dream", "driver", "drum", "duck", "dusk", "dust", "duty", 
  "eagle", "ear", "earth", "eastern", "effect", "effort", "elder", "elevator", "energy", "engine", 
  "entrance", "envelope", "equal", "escape", "exam", "explanation", "extra", "eye", "famous", "fan", 
  "fancy", "farm", "fashion", "feather", "fever", "fence", "field", "fight", "file", "fireman", "fish", 
  "flame", "flight", "flood", "floor", "flour", "flu", "fog", "folder", "forehead", "forest", "fort", 
  "fountain", "fox", "frame", "freak", "freezer", "frog", "frown", "fry", "gallery", "garage", "garbage", 
  "garden", "garlic", "gas", "ghost", "giant", "gift", "ginger", "glass", "glove", "goal", "golf", 
  "grandchild", "grandson", "grape", "grocery", "ground", "group", "guitar", "gum", "habit", "hammer", 
  "handle", "harm", "hat", "headache", "health", "heel", "herb", "hero", "history", "hole", "holiday", 
  "honey", "hook", "horn", "horse", "host", "hotel", "hug", "hunter", "hurry", "husband", "hut", "ice", 
  "iceberg", "idea", "illness", "image", "insect", "instant", "interest", "internet", "interview", 
  "island", "jelly", "joke", "journey", "joy", "jungle", "kangaroo", "ketchup", "keyboard", "kettle", 
  "knee", "knife", "knight", "knot", "ladder", "lady", "lake", "land", "language", "lap", "law", "leaf", 
  "lemon", "letter", "lettuce", "library", "lid", "line", "lion", "lip", "location", "lock", "luggage", 
  "mail", "map", "market", "match", "mate", "meadow", "meal", "meat", "meeting", "melon", "memory", 
  "metal", "mile", "mirror", "mistake", "mixture", "mobile", "monkey", "monster", "mood", "moon", "mosque", 
  "mouse", "movie", "mud", "museum", "mushroom", "music", "nail", "napkin", "necklace", "nephew", 
  "niece", "noise", "north", "notebook", "novel", "nurse", "nut", "ocean", "offer", "office", "oil", 
  "opinion", "orange", "oven", "owner", "page", "paint", "painter", "palace", "palm", "pan", "panda", 
  "paper", "parade", "parent", "park", "parrot", "party", "path", "peanut", "pear", "pen", "pencil", 
  "pepper", "per", "person", "piano", "pie", "pig", "pilot", "pin", "pineapple", "place", "planet", 
  "plant", "plastic", "plate", "plumber", "pocket", "poem", "poet", "police", "pool", "popcorn", "porter", 
  "pot", "prawn", "price", "prize", "pumpkin", "puppy", "puzzle", "queen", "question", "quiet", "quiz", 
  "rabbit", "race", "radio", "rail", "rain", "rainbow", "reason", "recipe", "rectangle", "refrigerator", 
  "resort", "result", "reward", "rhythm", "rice", "ride", "ring", "river", "road", "robot", "roof", 
  "room", "rope", "rose", "route", "runner", "safe", "sail", "salad", "salary", "sale", "sand", "sandwich", 
  "sauce", "saw", "scale", "scene", "schedule", "science", "score", "screen", "season", "seed", "self", 
  "seller", "service", "shade", "shadow", "shape", "shark", "shelf", "shell", "shock", "shoe", "shop", 
  "shore", "shoulder", "shovel", "shrimp", "sight", "signal", "silver", "sink", "sister", "skate", "skin", 
  "skirt", "sky", "slab", "slide", "smell", "smile", "snake", "snow", "soap", "soccer", "sock", "soda", 
  "soil", "soldier", "song", "soup", "space", "spade", "speaker", "spell", "spider", "spine", "spirit", 
  "spoon", "spring", "square", "stadium", "stage", "stair", "stamp", "star", "station", "statue", "steak", 
  "steam", "steel", "stem", "step", "stick", "stone", "store", "storm", "story", "stove", "street", 
  "string", "structure", "student", "study", "subway", "sugar", "summer", "sun", "swan", "sweater", 
  "swim", "swing", "sword", "system", "table", "tail", "taxi", "team", "teapot", "tear", "telephone", 
  "television", "temperature", "tent", "term", "text", "theater", "theme", "thumb", "ticket", "tie", 
  "time", "title", "toast", "toilet", "tomato", "tool", "tooth", "topic", "torch", "tour", "tower", 
  "town", "track", "tractor", "traffic", "train", "tray", "tree", "trip", "truck", "truth", "tune", 
  "tunnel", "turkey", "turtle", "twist", "type", "umbrella", "uncle", "uniform", "universe", "vacation", 
  "valley", "van", "vase", "vehicle", "village", "violet", "voice", "volcano", "volunteer", "waiter", 
  "wallet", "wallpaper", "walnut", "water", "weather", "wedding", "week", "wheel", "whistle", "window", 
  "wing", "winter", "wish", "wolf", "woman", "wood", "world", "worm", "wrist", "yard", "year", "yogurt", 
  "zebra", "zoo", "ability", "actor", "address", "advice", "aeroplane", "afternoon", "age", "agreement", "airplane", 
  "alarm", "album", "amusement", "anchor", "angle", "ant", "ankle", "answer", "apology", "appointment", 
  "apricot", "arch", "argument", "armchair", "arrival", "artist", "assignment", "assistant", "attempt", 
  "attic", "aunt", "avocado", "baby", "backpack", "bacon", "badger", "bag", "balance", "ball", "balloon", 
  "bamboo", "banker", "barbecue", "barn", "base", "basin", "basket", "bat", "battery", "bean", "beast", 
  "beaver", "bee", "beer", "beetle", "beginner", "bench", "bet", "bingo", "biscuit", "bite", "blackboard", 
  "blank", "bleach", "blessing", "blizzard", "blush", "boar", "boat", "bog", "boil", "bolt", "bomb", 
  "booklet", "booth", "border", "bother", "bouquet", "bowl", "brain", "branch", "brass", "breakfast", 
  "breeze", "brick", "broccoli", "broom", "brother", "bubble", "bucket", "buffalo", "bulb", "bunker", 
  "burger", "bush", "butterfly", "cabbage", "cabin", "cable", "cactus", "cage", "cake", "calf", "can", 
  "candy", "cane", "canoe", "cape", "captain", "caravan", "card", "carpet", "cashier", "cassette", 
  "castle", "caterpillar", "cathedral", "cauliflower", "cave", "ceiling", "cell", "cellar", "cement", 
  "century", "chain", "charm", "cheese", "chemist", "cheque", "chestnut", "chicken", "chili", "chimney", 
  "chin", "choice", "cider", "circle", "circus", "clam", "clamp", "clap", "claw", "cliff", "clinic", 
  "clock", "closet", "clothes", "club", "coach", "coal", "coast", "collar", "column", "comedian", 
  "comfort", "committee", "compass", "composer", "concert", "condition", "cone", "conductor", "cone", 
  "continent", "copy", "coral", "corner", "costume", "couch", "cousin", "cover", "cradle", "craft", 
  "crane", "crawl", "credit", "crew", "cricket", "crime", "cross", "cruise", "crust", "cucumber", 
  "cupboard", "cure", "curtain", "cushion", "custard", "dad", "damage", "dance", "darkness", "date", 
  "debt", "decision", "deer", "degree", "delivery", "dentist", "department", "desert", "desire", 
  "desk", "detective", "dew", "diamond", "diet", "dig", "dirt", "distance", "dive", "division", 
  "doctor", "doll", "dolphin", "donor", "donut", "doorway", "dot", "double", "doubt", "dragon", 
  "drawer", "dreamer", "dressing", "drizzle", "drop", "drum", "duck", "dump", "dust", "duty", 
  "dye", "eagle", "ear", "east", "echo", "eclipse", "editor", "effect", "effort", "eggplant", 
  "elbow", "electronic", "emergency", "engine", "engineer", "envelope", "eraser", "error", 
  "escalator", "eve", "event", "exchange", "exit", "eye", "fable", "factory", "failure", 
  "family", "fan", "farewell", "farmer", "fashion", "father", "feast", "feather", "ferry", 
  "field", "figure", "finger", "firefighter", "first", "fisherman", "flame", "flash", "flat", 
  "flight", "flood", "flour", "fog", "foil", "folder", "forest", "fork", "fortune", "founder", 
  "fox", "frame", "freedom", "freeze", "friend", "frog", "frost", "fruit", "fudge", "fuel", 
  "furniture", "gallery", "garage", "garbage", "garden", "gate", "genius", "gesture", "giant", 
  "gift", "gingerbread", "giraffe", "glacier", "glove", "goal", "gold", "goodbye", "gown", 
  "grace", "granddaughter", "grape", "grass", "greeting", "grill", "grin", "grocery", "ground", 
  "guest", "guitarist", "gum", "gym", "habit", "hammer", "handle", "harmony", "hat", "health", 
  "heel", "helmet", "hike", "hippo", "history", "holiday", "honey", "hook", "hope", "horizon", 
  "hospital", "host", "hotel", "household", "hut", "iceberg", "icon", "idea", "identity", 
  "illness", "inbox", "income", "inflation", "ink", "insect", "instructor", "intention", "interior", 
  "island", "item", "ivy", "jacket", "jellyfish", "jewel", "journal", "judge", "jungle", "junk", 
  "kangaroo", "keeper", "kettle", "kidney", "kilo", "kilometer", "kitchen", "kite", "knee", 
  "knight", "knot", "ladder", "ladybug", "lake", "language", "lap", "lawn", "layer", "leather", 
  "lemonade", "length", "lettuce", "library", "license", "lifestyle", "lightning", "limb", 
  "lime", "line", "liver", "lizard", "load", "loan", "lobster", "log", "loose", "loyalty", 
  "lunchbox", "lung", "lyric", "machine", "madam", "mailbox", "main", "mammal", "manager", 
  "map", "marble", "market", "martial", "mask", "mat", "match", "meadow", "meaning", "measure", 
  "mechanic", "melody", "menu", "message", "meter", "microphone", "microwave", "middle", "mile", 
  "miner", "mixer", "mood", "moonlight", "morning", "mosquito", "mountain", "mouse", "mud", 
  "museum", "musician", "mystery", "myth", "nail", "nature", "neighborhood", "nephew", "network", 
  "news", "nickname", "noodle", "north", "nurse", "object", "occasion", "ocean", "offer", 
  "office", "olive", "onion", "opinion", "orange", "orchard", "oven", "owner", "package", 
  "paddle", "page", "pain", "painter", "pair", "pajamas", "palace", "palm", "parrot", 
  "passenger", "pearl", "peg", "pencil", "pepper", "perfume", "pest", "phone", "phrase", 
  "picnic", "picture", "pier", "pilot", "pine", "pizza", "planet", "plastic", "plate", 
  "plumber", "poem", "poet", "pond", "pool", "porcupine", "position", "post", "poster", 
  "pot", "potato", "prayer", "present", "priest", "problem", "process", "product", "profit", 
  "program", "project", "prophet", "protein", "protest", "pulse", "pumpkin", "puzzle", 
  "quality", "quantity", "quilt", "quote", "rabbit", "radio", "railway", "rainbow", "receipt", 
  "record", "referee", "region", "rescue", "reserve", "resort", "resource", "response", 
  "restaurant", "revolution", "reward", "rice", "ring", "river", "robot", "rocket", 
  "roof", "rope", "route", "routine", "ruby", "rug", "rule", "saddle", "safety", "salmon", 
  "salt", "sand", "sapphire", "scarf", "scene", "science", "score", "sea", "season", 
  "secret", "seed", "shade", "shadow", "shape", "shell", "shirt", "shoe", "shore", 
  "sibling", "silk", "silver", "sink", "skateboard", "sketch", "skill", "skull", "sky", 
  "slip", "smell", "smoke", "snail", "snake", "soap", "society", "sock", "soil", "solar", 
  "soldier", "song", "space", "spark", "spider", "spoon", "spray", "square", "squirrel", 
  "stadium", "stage", "stamp", "star", "station", "statue", "sticker", "storm", "stream", 
  "student", "suitcase", "sun", "surprise", "swan", "swim", "switch", "system", "table", 
  "tail", "talent", "tank", "taxi", "team", "teapot", "teacher", "tent", "tiger", 
  "time", "title", "toast", "toe", "together", "tool", "tooth", "topic", "towel", 
  "tower", "track", "trail", "tree", "triangle", "trombone", "truck", "truth", "tuna", 
  "tunnel", "turkey", "turtle", "typewriter", "uncle", "umbrella", "uniform", "universe", 
  "vaccine", "valley", "van", "vase", "vegetable", "vehicle", "violin", "vocabulary", 
  "volcano", "volleyball", "vote", "wagon", "waist", "wallet", "wave", "wedding", 
  "weekend", "weight", "whale", "wheel", "whistle", "window", "wing", "winner", "winter", 
  "wizard", "wolf", "wonder", "world", "wrist", "yard", "yogurt", "zebra"
];

export const A2_B2 = [
  'ability', 'abundant', 'accident', 'adventure', 'advocate', 'affection', 'afternoon', 'agreement', 'alliance',
  'amazing', 'ambition', 'analysis', 'ancient', 'anger', 'annual', 'anxiety', 'appearance', 'applause', 'appreciate',
  'approval', 'arrangement', 'artist', 'asleep', 'athletic', 'atmosphere', 'attention', 'attitude', 'authentic',
  'average', 'balance', 'beautiful', 'belief', 'beneath', 'benefit', 'bizarre', 'blessing', 'bold', 'bravery', 'bright',
  'brotherhood', 'burden', 'calm', 'capable', 'career', 'caring', 'celebrate', 'centered', 'challenge', 'changeable',
  'charity', 'charming', 'cheerful', 'classic', 'clever', 'closer', 'colorful', 'comfort', 'common', 'compassion',
  'complete', 'confidence', 'conquer', 'constant', 'content', 'cooperative', 'courage', 'creative', 'crisis',
  'cultural', 'curious', 'current', 'custom', 'damage', 'danger', 'daydream', 'decisive', 'definite', 'delight',
  'dependable', 'deserve', 'desperate', 'determined', 'different', 'dignity', 'diplomatic', 'discovery', 'distinct',
  'diverse', 'dominant', 'doubtful', 'dream', 'drowsy', 'dynamic', 'eager', 'earthy', 'education', 'effective',
  'effort', 'elegant', 'emotion', 'energy', 'engage', 'enormous', 'enthusiastic', 'essential', 'eternal', 'ethics',
  'evaluate', 'eventful', 'evident', 'examine', 'excellent', 'excited', 'expect', 'experience', 'expert', 'expressive',
  'faithful', 'famous', 'fascinate', 'fashion', 'favor', 'fearless', 'feature', 'fierce', 'figure', 'flexible', 'focus',
  'fortunate', 'frequent', 'friendly', 'frighten', 'fulfill', 'future', 'genuine', 'global', 'golden', 'graceful',
  'gradual', 'grateful', 'habitual', 'handsome', 'harmony', 'healthy', 'heroic', 'honest', 'hopeful', 'humble',
  'ideal', 'impact', 'important', 'improve', 'inclined', 'incredible', 'independent', 'innocent', 'inspire', 'intense',
  'interest', 'intimate', 'invincible', 'jovial', 'joyful', 'justice', 'keen', 'kindness', 'knowledge', 'laughter',
  'leader', 'liberty', 'lifelong', 'limitless', 'loyalty', 'lucky', 'magnificent', 'marvel', 'meaning', 'mellow',
  'memorable', 'merit', 'mighty', 'mindful', 'miracle', 'modest', 'moment', 'motion', 'mystery', 'natural', 'noble',
  'noticeable', 'nurture', 'objective', 'obstacle', 'observe', 'obvious', 'offense', 'optimal', 'orderly', 'organic',
  'outcome', 'outstanding', 'overcome', 'palace', 'passion', 'patient', 'peaceful', 'permanent', 'persistent',
  'personal', 'persuade', 'philosophy', 'pleasure', 'polite', 'popular', 'positive', 'potential', 'precious', 'prefer',
  'prepare', 'present', 'pretty', 'pride', 'primary', 'proactive', 'profound', 'progress', 'promise', 'prompt',
  'prosper', 'protect', 'proud', 'quality', 'quest', 'quiet', 'radiant', 'rare', 'realistic', 'recognize', 'reliable',
  'remarkable', 'resource', 'respect', 'responsible', 'reveal', 'richness', 'rightful', 'risk', 'robust', 'romantic',
  'sacred', 'safety', 'satisfaction', 'secure', 'sensible', 'sensitive', 'serenity', 'significant', 'silent',
  'sincere', 'skillful', 'smart', 'social', 'solid', 'spark', 'special', 'spirit', 'splendid', 'stability', 'steady',
  'strength', 'strong', 'structure', 'study', 'style', 'success', 'suitable', 'sunshine', 'superior', 'supportive',
  'surprise', 'sustain', 'sympathy', 'talented', 'thankful', 'thorough', 'thoughtful', 'tolerant', 'tranquil', 'unique',
  'unity', 'universe', 'uplift', 'value', 'vibrant', 'victory', 'vision', 'vital', 'volunteer', 'wealth', 'welcome',
  'wisdom', 'wonderful', 'worthy', 'youthful', 'zealous', 'admire', 'advance', 'affection', 'airborne', 'announce',
  'anticipate', 'appreciate', 'assume', 'attract', 'bargain', 'believe', 'calculate', 'celebrate', 'character',
  'circumstance', 'classify', 'collective', 'command', 'commerce', 'communicate', 'conclude', 'construct', 'convey',
  'create', 'debate', 'decorate', 'defend', 'demonstrate', 'describe', 'devote', 'determine', 'differentiate',
  'discuss', 'discover', 'distinguish', 'elaborate', 'elevate', 'eliminate', 'encourage', 'endorse', 'entertain', 'establish', 'estimate', 'evaluate', 'execute', 'exercise', 'explain', 'explore', 'express', 'facilitate', 'focus',
  'formulate', 'generate', 'govern', 'identify', 'illustrate', 'implement', 'improve', 'influence', 'instruct',
  'integrate', 'interact', 'interpret', 'investigate', 'involve', 'judge', 'justify', 'label', 'maintain', 'manage',
  'measure', 'modify', 'monitor', 'motivate', 'negotiate', 'operate', 'organize', 'perform', 'perceive', 'persuade',
  'portray', 'prepare', 'prioritize', 'promote', 'propose', 'protect', 'question', 'realize', 'recommend', 'reflect',
  'reinforce', 'relate', 'represent', 'research', 'resolve', 'respond', 'restrict', 'secure', 'select', 'sequence',
  'simulate', 'specify', 'structure', 'summarize', 'support', 'sustain', 'testify', 'train', 'transform', 'translate',
  'validate', 'visualize', 'volunteer', 'witness',  'abandon', 'account', 'achieve', 'activity', 'advantage', 'adventure', 'affair', 'agency', 'airport', 'allowance',
  'amusement', 'ancestor', 'anxiety', 'apology', 'approval', 'arrival', 'article', 'assistance', 'assume', 'attraction',
  'backyard', 'balance', 'banquet', 'barrier', 'bedroom', 'benefit', 'bicycle', 'biology', 'blanket', 'blossom',
  'boundary', 'briefing', 'brilliant', 'brochure', 'brother', 'business', 'calendar', 'campsite', 'capture', 'carpet',
  'carrier', 'celebrity', 'ceremony', 'charity', 'citizen', 'clothing', 'collect', 'comfort', 'command', 'comment',
  'community', 'concert', 'confuse', 'confusion', 'connect', 'container', 'contest', 'contrast', 'convenience',
  'courage', 'creature', 'crystal', 'curious', 'custom', 'darkness', 'decision', 'decorate', 'deliver', 'delight',
  'density', 'describe', 'desire', 'destiny', 'dialogue', 'digital', 'disaster', 'discuss', 'display', 'distance',
  'district', 'divorce', 'document', 'domestic', 'double', 'download', 'drawer', 'economy', 'educate', 'effort',
  'election', 'emotion', 'empathy', 'employee', 'engineer', 'enhance', 'entrance', 'episode', 'equality', 'escape',
  'evidence', 'exciting', 'exercise', 'exhibit', 'expense', 'explain', 'explore', 'express', 'failure', 'fashion',
  'feature', 'feather', 'festival', 'fiction', 'finance', 'fireplace', 'fishing', 'fitness', 'flagship', 'flavor',
  'flexible', 'forehead', 'forever', 'forgive', 'frequent', 'friend', 'furniture', 'gallery', 'gateway', 'generate',
  'genius', 'gesture', 'glacier', 'glamour', 'glimmer', 'grammar', 'grateful', 'greeting', 'grocery', 'habitat',
  'harmony', 'harvest', 'healthy', 'hearing', 'heaven', 'helicopter', 'heritage', 'holiday', 'homework', 'honesty',
  'hopeful', 'horizon', 'horror', 'household', 'humanity', 'hunger', 'hygiene', 'identify', 'imagine', 'impress',
  'include', 'infinite', 'influence', 'informer', 'inherit', 'inquiry', 'insect', 'instant', 'install', 'inspire',
  'instruct', 'intense', 'interest', 'journey', 'justice', 'kitchen', 'landlord', 'landscape', 'language', 'laughter',
  'lawyer', 'lecture', 'library', 'license', 'lifetime', 'lighter', 'location', 'lonely', 'loyalty', 'machine',
  'magnetic', 'maintain', 'manager', 'mansion', 'massage', 'maximum', 'measure', 'medical', 'meeting', 'mention',
  'message', 'miracle', 'mixture', 'moment', 'monitor', 'mystery', 'natural', 'network', 'neutral', 'notebook',
  'nuclear', 'nurture', 'observe', 'obvious', 'officer', 'operate', 'opinion', 'opposite', 'organic', 'outcome',
  'outdoor', 'outlook', 'package', 'painful', 'palace', 'partner', 'pattern', 'payment', 'peaceful', 'perfect',
  'perform', 'permit', 'pioneer', 'plastic', 'pleasure', 'pocket', 'popular', 'portion', 'postpone', 'pottery',
  'poverty', 'precise', 'predict', 'premium', 'present', 'pressure', 'preview', 'primary', 'princess', 'privacy',
  'process', 'produce', 'product', 'program', 'project', 'promise', 'protect', 'protest', 'provide', 'purpose',
  'quality', 'quarter', 'radical', 'rainbow', 'ranger', 'rapidly', 'realize', 'receive', 'recover', 'refresh',
  'release', 'removal', 'replace', 'request', 'require', 'rescue', 'reserve', 'respect', 'response', 'restore',
  'revenue', 'reverse', 'reward', 'rhythm', 'romantic', 'routine', 'sailing', 'sample', 'sanity', 'satellite',
  'satisfy', 'science', 'section', 'secure', 'shelter', 'silence', 'similar', 'simple', 'sincere', 'society',
  'software', 'sponsor', 'stadium', 'strange', 'student', 'subject', 'suggest', 'support', 'surface', 'survive',
  'symbol', 'talent', 'teacher', 'technology', 'television', 'terrific', 'theater', 'together', 'tourism', 'traffic',
  'transform', 'translate', 'treasure', 'triangle', 'typical', 'universe', 'upgrade', 'upstairs', 'valuable',
  'variety', 'vehicle', 'victory', 'village', 'virtual', 'visitor', 'volcano', 'volunteer', 'warning', 'welcome',
  'whisper', 'willing', 'witness', 'wonderful', 'workshop', 'worship', 'writer', 'yogurt', 'youthful', 'academy', 'airline', 'airport', 'amazing', 'analogy', 'analyze', 'animate', 'appeal', 'arrival', 'article', 'artist',
  'asleep', 'athlete', 'attach', 'attempt', 'average', 'balance', 'barrier', 'battery', 'billion', 'blanket',
  'breathe', 'brother', 'budget', 'cabinet', 'capture', 'carbon', 'careful', 'carpet', 'catalog', 'central', 'change',
  'channel', 'charity', 'cheaply', 'chemist', 'climate', 'closet', 'comfort', 'common', 'compete', 'complex',
  'concert', 'connect', 'content', 'contest', 'cooking', 'correct', 'cottage', 'council', 'counter', 'country',
  'culture', 'curious', 'curtain', 'damage', 'danger', 'darken', 'debate', 'decade', 'decent', 'decide', 'decrease',
  'default', 'defend', 'degree', 'delay', 'deliver', 'density', 'deposit', 'design', 'detect', 'device', 'dietary',
  'differ', 'digital', 'dinner', 'direct', 'distant', 'divide', 'doctor', 'double', 'draft', 'drama', 'dreamer',
  'driver', 'dynamic', 'eager', 'easily', 'economy', 'effort', 'elect', 'element', 'elite', 'energy', 'engage',
  'engine', 'ensure', 'entire', 'equal', 'escape', 'estate', 'ethical', 'ethnic', 'evening', 'evolve', 'expert',
  'export', 'extend', 'family', 'fashion', 'father', 'fearful', 'feather', 'female', 'fighter', 'filter', 'finish',
  'flavor', 'flood', 'follow', 'former', 'fortune', 'future', 'garage', 'garden', 'general', 'genetic', 'genuine',
  'global', 'grateful', 'happen', 'heaven', 'helmet', 'heroic', 'highlight', 'honor', 'household', 'humor', 'hunter',
  'ignore', 'illegal', 'impact', 'imply', 'income', 'inform', 'injure', 'inspire', 'intend', 'invest', 'involve',
  'issue', 'jacket', 'jogger', 'junior', 'keeper', 'kitchen', 'ladder', 'laptop', 'lawyer', 'leader', 'legend',
  'length', 'liberty', 'likely', 'limit', 'liver', 'locate', 'lucky', 'lunar', 'major', 'manage', 'market', 'matter',
  'media', 'metal', 'model', 'modern', 'moment', 'monitor', 'morale', 'motive', 'muscle', 'myself', 'native', 'nature', "abandon", "ability", "absorb", "accent", "accommodation", "achievement", "acquire", 
  "adaptation", "address", "administration", "admire", "advantage", "advertisement", 
  "advice", "affair", "affection", "agency", "agriculture", "alarm", "alcohol", "ambition", 
  "analysis", "ancestor", "angel", "ankle", "announcement", "anxiety", "apology", "appearance", 
  "appetite", "application", "appointment", "appreciation", "approach", "architecture", 
  "area", "argument", "aroma", "arrangement", "arrival", "ashamed", "aspect", "assembly", 
  "assignment", "assistance", "atmosphere", "attitude", "attraction", "authority", "awareness", 
  "background", "baggage", "baker", "balance", "balloon", "ban", "barber", "barrier", 
  "battery", "behavior", "belief", "benefit", "betray", "bicycle", "biography", "birthplace", 
  "biscuit", "blanket", "blessing", "block", "bloom", "blush", "board", "boast", "bond", 
  "border", "boring", "bother", "boundary", "branch", "bravery", "breeze", "briefcase", 
  "broadcast", "brochure", "budget", "bump", "butterfly", "cable", "calculate", "campaign", 
  "capacity", "capital", "captain", "capture", "careful", "cashier", "category", "celebration", 
  "century", "ceremony", "challenge", "champion", "chaos", "character", "charge", "charity", 
  "charm", "chase", "chemistry", "childhood", "chimney", "chocolate", "choice", "circuit", 
  "citizen", "civilization", "clarity", "climate", "clothing", "clue", "coincidence", 
  "collar", "collection", "college", "colony", "column", "comfort", "command", "comment", 
  "commerce", "commission", "commitment", "community", "companion", "comparison", "compete", 
  "complaint", "complex", "composer", "composition", "concept", "concern", "concert", 
  "condition", "conference", "conflict", "confusion", "consequence", "consideration", 
  "consist", "construction", "contact", "contest", "context", "contract", "contribution", 
  "control", "convenience", "convention", "conviction", "cooperation", "corner", "council", 
  "countryside", "courage", "crash", "creation", "creature", "criticism", "cultural", 
  "curiosity", "current", "curtain", "custom", "cycle", "damage", "dangerous", "decrease", 
  "dedication", "definition", "delay", "delivery", "demand", "democracy", "demonstration", 
  "density", "departure", "dependent", "depression", "deserve", "destination", "destruction", 
  "development", "device", "diet", "difference", "difficulty", "digital", "dignity", 
  "direction", "disaster", "discipline", "discovery", "discussion", "disease", "display", 
  "distance", "disturbance", "diverse", "divorce", "document", "dominant", "donation", 
  "dot", "doubt", "draft", "dramatic", "drawing", "dreamer", "dress", "duration", 
  "dust", "dynamic", "earthquake", "ease", "economics", "efficiency", "election", "elevator", 
  "embarrassment", "emergency", "emotion", "employee", "encounter", "energy", "engagement", 
  "engineer", "enjoyment", "enthusiasm", "environment", "episode", "equality", "equipment", 
  "error", "essential", "estimate", "evidence", "exaggeration", "examination", "exception", 
  "excitement", "exercise", "existence", "expansion", "expectation", "experience", "experiment", 
  "explanation", "exploration", "explosion", "expression", "extension", "extreme", "fabric", 
  "facility", "failure", "familiar", "family", "fantasy", "farewell", "farmer", "fashion", 
  "fatal", "favor", "feedback", "festival", "fiction", "field", "fierce", "figure", "filter", 
  "finance", "firefighter", "flexibility", "focus", "folder", "foundation", "fragment", 
  "frank", "freedom", "friendship", "fuel", "furniture", "future", "gallery", "gathering", 
  "gender", "genius", "gesture", "glance", "goal", "governor", "gradual", "graduate", 
  "grant", "gravity", "greatness", "grocery", "guideline", "guilt", "habit", "happiness", 
  "hardship", "headline", "health", "height", "heritage", "hero", "hesitation", "highlight", 
  "historian", "holiday", "horizon", "hospital", "host", "household", "humanity", "humble", 
  "humidity", "humor", "hunger", "hurry", "idea", "ideal", "identity", "illusion", "imagination", 
  "impact", "improvement", "incentive", "incident", "income", "independence", "indicator", 
  "individual", "industry", "influence", "ingredient", "initiative", "innocence", "insight", 
  "inspector", "instance", "instruction", "insurance", "interaction", "interest", "interpretation", 
  "introduction", "investigation", "investment", "involvement", "isolation", "item", 
  "jelly", "journal", "judge", "justice", "keeper", "kingdom", "knowledge", "landscape", 
  "language", "laughter", "lawn", "leader", "leadership", "lecture", "legend", "length", 
  "leopard", "lesson", "liberty", "library", "lifestyle", "lightning", "limitation", 
  "literature", "location", "loyalty", "luxury", "magazine", "magnet", "maintenance", 
  "mammal", "manager", "manufacture", "maple", "marriage", "masterpiece", "match", 
  "material", "measurement", "mechanic", "medicine", "membership", "memory", "mentality", 
  "merit", "message", "metal", "meter", "microphone", "migration", "military", "minister", 
  "minority", "mirror", "mission", "mistake", "mixture", "modern", "molecule", "moment", 
  "monitor", "mood", "movement", "murder", "musician", "mystery", "myth", "narrative", 
  "native", "navigation", "necessity", "network", "nightmare", "nonsense", "novel", "nutrition", 
  "obligation", "observation", "occasion", "occupation", "offense", "officer", "operation", 
  "opinion", "opportunity", "option", "orbit", "organizer", "orientation", "origin", "outcome", 
  "output", "overall", "overlap", "package", "pain", "parallel", "parliament", "passage", 
  "passenger", "patience", "payment", "percentage", "performance", "period", "permission", 
  "perseverance", "pest", "phenomenon", "philosophy", "photograph", "phrase", "physical", 
  "pilot", "pioneer", "planet", "platform", "pleasure", "poet", "policy", "politics", 
  "portion", "position", "possession", "potential", "poverty", "practical", "preference", 
  "prejudice", "preparation", "presentation", "prestige", "pressure", "prevention", 
  "principle", "privacy", "procedure", "producer", "product", "profession", "profit", 
  "program", "progress", "promotion", "proof", "property", "proportion", "proposal", 
  "protection", "protein", "protest", "psychology", "publication", "publisher", "pursuit", 
  "quantity", "quality", "quotation", "racism", "rainforest", "random", "rating", "reaction", 
  "reason", "recall", "recognition", "recommendation", "reflection", "refugee", "region", 
  "regret", "relationship", "relaxation", "relevance", "reliable", "remedy", "report", 
  "representation", "request", "reputation", "rescue", "reservation", "resolution", "resource", 
  "responsibility", "restriction", "revenue", "review", "reward", "rhythm", "ritual", 
  "routine", "rumor", "sacrifice", "safety", "salary", "sanctuary", "schedule", "scientist", 
  "search", "section", "security", "sensation", "sensitive", "sentence", "session", "settlement", 
  "shadow", "shape", "shelter", "shift", "shopping", "signature", "silence", "similarity", 
  "simulation", "situation", "slogan", "software", "solution", "sophistication", "souvenir", 
  "specialist", "spectacle", "speed", "spice", "spiritual", "splendor", "spokesperson", 
  "sponsor", "spread", "spring", "stadium", "statement", "statue", "status", "storage", 
  "stranger", "strategy", "strength", "structure", "student", "substance", "suburb", 
  "success", "suggestion", "supervision", "supplier", "supply", "support", "surface", 
  "survival", "sympathy", "system", "table", "talent", "target", "technique", "technology", 
  "temperature", "territory", "terror", "theme", "therapy", "thief", "threat", "ticket", 
  "time", "tolerance", "tournament", "tradition", "traffic", "training", "transaction", 
  "transition", "transportation", "treasure", "treatment", "tribute", "trophy", "trust", 
  "tutor", "typical", "unemployment", "universe", "update", "upgrade", "utility", "vacation", 
  "validity", "vampire", "variation", "vehicle", "version", "victory", "viewpoint", 
  "violence", "visitor", "volume", "voting", "wage", "warehouse", "warmth", "warrior", 
  "waste", "wealth", "weapon", "weather", "welfare", "whisper", "wisdom", "witness", 
  "wonder", "worker", "wound", "wrist", "youth", "zone"
];

export const B2_C2 = [
  'abundance', 'acclaimed', 'accomplishment', 'accumulation', 'adaptation', 'adept', 'adjective', 'advocate', 'alleviate',
  'ambiguity', 'ambitious', 'analytical', 'anecdote', 'antagonist', 'anticipation', 'apprehensive', 'aptitude', 'arbitrary',
  'aspiration', 'assimilate', 'astonishment', 'authenticity', 'autonomy', 'benevolent', 'biased', 'blatant', 'brevity',
  'brilliance', 'catastrophic', 'cautious', 'collaboration', 'commemorate', 'commendable', 'commodity', 'compassionate',
  'complexity', 'compliance', 'comprehensive', 'compromise', 'conceivable', 'conformity', 'connotation', 'consensus',
  'constituent', 'contemplation', 'contentious', 'contribution', 'conventional', 'conviction', 'copious', 'correspondent',
  'credibility', 'criticism', 'culminate', 'cultivation', 'cumulative', 'curiosity', 'declaration', 'dedication',
  'deficiency', 'definitive', 'deliberate', 'delicacy', 'detrimental', 'devotion', 'dignified', 'diligent', 'diplomatic',
  'disclosure', 'discrepancy', 'disposition', 'distinction', 'dominance', 'dynamic', 'eclectic', 'elaborate', 'elusive',
  'emancipation', 'embodiment', 'empathy', 'empowerment', 'endeavor', 'endorsement', 'enlightenment', 'enrichment',
  'enthusiasm', 'entrepreneurial', 'equilibrium', 'eradicate', 'espionage', 'estimation', 'etiquette', 'euphemism',
  'exaggeration', 'exemplary', 'exhaustive', 'existential', 'expectation', 'expedition', 'expertise', 'extravagant',
  'facilitate', 'fascination', 'fluctuation', 'formidable', 'fostering', 'foundation', 'fragmentation', 'framework',
  'fundamental', 'generosity', 'gratification', 'grievance', 'harmonious', 'harmony', 'hesitation', 'hierarchy', 'hilarity',
  'honorary', 'humility', 'hypothesis', 'idealistic', 'idiosyncratic', 'illustration', 'imminent', 'impartial', 'imperative',
  'implementation', 'implicit', 'implication', 'inaccessible', 'inadequate', 'incentive', 'inclination', 'incoherent',
  'incompatible', 'inconsistency', 'independence', 'indispensable', 'inefficiency', 'inevitable', 'influential',
  'infrastructure', 'initiative', 'innovation', 'insightful', 'integrity', 'intellectual', 'intensity', 'intermediate',
  'interpretation', 'intervention', 'intriguing', 'introspection', 'invigorate', 'involvement', 'isolation', 'justification',
  'lamentation', 'legitimate', 'liability', 'liberation', 'likelihood', 'linguistic', 'livelihood', 'longevity', 'lucidity',
  'magnanimous', 'manipulative', 'mastery', 'meaningful', 'mediation', 'melancholy', 'memorandum', 'metaphorical',
  'methodical', 'meticulous', 'milestone', 'mischievous', 'moderation', 'modification', 'monetary', 'monotony', 'mortality',
  'motivation', 'mystification', 'narrative', 'negligence', 'nomination', 'nonchalance', 'noteworthy', 'nurturing',
  'obligation', 'observation', 'obsession', 'obstacle', 'omission', 'opponent', 'opportunistic', 'optimism', 'overwhelming',
  'paradoxical', 'partnership', 'passionate', 'perception', 'perfectionism', 'peripheral', 'perplexing', 'perspective',
  'persistence', 'philosophical', 'plausibility', 'polarity', 'political', 'popularity', 'potentiality', 'precarious',
  'precedent', 'predicament', 'preference', 'preliminary', 'preservation', 'prestigious', 'probability', 'proclamation',
  'prodigious', 'proficiency', 'prominent', 'propensity', 'proportionate', 'prospective', 'protagonist', 'provocative',
  'prudence', 'qualification', 'quantitative', 'quintessential', 'radical', 'rationale', 'realization', 'reassurance',
  'receptivity', 'reciprocity', 'recognizable', 'recommendation', 'reconstruct', 'recreation', 'reformation', 'regression',
  'rehabilitation', 'reinforcement', 'reluctance', 'remembrance', 'remoteness', 'reputation', 'reservation', 'resilience',
  'resistant', 'respectable', 'retrospective', 'revelation', 'rigorous', 'safeguard', 'sanctuary', 'satirical', 'scholarly',
  'segmentation', 'sensation', 'sentimental', 'significance', 'similarity', 'simultaneous', 'skepticism', 'sophisticated', 'spontaneous', 'stability', 'standpoint', 'stimulating', 'strategic', 'structural', 'subjective', 'substantial',
  'substitute', 'succession', 'sufficient', 'superiority', 'supplementary', 'susceptibility', 'sustainability', 'symbolic',
  'symmetry', 'synthesis', 'tactful', 'tendency', 'tentative', 'termination', 'tolerance', 'tremendous', 'typical',
  'uncertainty', 'underlying', 'unequivocal', 'unification', 'unorthodox', 'unpredictable', 'unprecedented', 'unquestioned',
  'validity', 'valuable', 'veneration', 'ventilation', 'versatile', 'vibrancy', 'victorious', 'visualization', 'volatility',
  'vulnerability', 'wholesome', 'wisdom', 'workplace', 'worthwhile', 'zealot', 'acclimate', 'acumen', 'advisable',
  'affiliation', 'aggressive', 'altruism', 'ambiguity', 'animosity', 'anticipatory', 'applicable', 'aspiration',
  'assumption', 'attainment', 'benevolence', 'calamity', 'cohesive', 'collaborative', 'commendable', 'competence',
  'congruence', 'conscientious', 'constructive', 'continuity', 'creativity', 'culpability', 'curiosity', 'deductible',
  'deficiency', 'detrimental', 'discreet', 'dissension', 'distraction', 'dynamism', 'eloquent', 'epitome', 'exemplify',
  'extraordinary', 'feasibility', 'fortitude', 'gratification', 'heroism', 'hospitable', 'hypocrisy', 'imaginative',
  'impermanence', 'impervious', 'impetus', 'improbable', 'incapable', 'incarnation', 'indecisive', 'inevitable',
  'infallible', 'ingenuity', 'integral', 'interplay', 'intuition', 'justification', 'liberation', 'linguistic', 'longevity',
  'malicious', 'meticulous', 'momentum', 'mutuality', 'neutrality', 'nourishment', 'obsession', 'omnipotent', 'openness',
  'optimism', 'paradigm', 'passionate', 'patronage', 'perception', 'peripheral', 'perpetual', 'plausibility', 'popularity',
  'potential', 'precaution', 'predicament', 'preferable', 'prevalent', 'proactive', 'prodigy', 'profound', 'prominent',
  'prosperous', 'provocative', 'punctual', 'radiance', 'reassuring', 'reciprocal', 'recognition', 'reflective', 'reliance',
  'relevant', 'resilience', 'resourceful', 'respectful', 'restoration', 'revelation', 'ruthless', 'sagacity', 'sanctity',
  'savor', 'sensitive', 'serenity', 'significant', 'sincerity', 'sobriety', 'sophistication', 'speculate', 'steadfast',
  'strategy', 'stringent', 'structural', 'stubborn', 'submission', 'sublime', 'subtlety', 'success',  'abandonment', 'absorption', 'abundance', 'acquaintance', 'adaptability', 'adherence', 'admission', 'advancement',
  'affiliation', 'aggregate', 'agriculture', 'allocation', 'alteration', 'amplify', 'analytical', 'anonymity', 'appraisal',
  'arbitrary', 'articulate', 'assessment', 'assumption', 'atmospheric', 'authenticity', 'bargaining', 'behavioural',
  'breakthrough', 'bureaucratic', 'calculative', 'capability', 'certification', 'civilization', 'clarification',
  'collaboration', 'collateral', 'commemorate', 'commentary', 'commitment', 'comparable', 'compensate', 'complement',
  'complexity', 'compliance', 'composure', 'comprehensive', 'conceptual', 'conclusion', 'condensation', 'conductivity',
  'configuration', 'conglomerate', 'congregate', 'consciousness', 'conservation', 'consistency', 'consolidate',
  'conspiratorial', 'constellation', 'contemplative', 'contributor', 'controversy', 'convergence', 'correlation',
  'creativity', 'culminate', 'curiosity', 'deceleration', 'dedication', 'definitive', 'degradation', 'demonstration',
  'dependency', 'depletion', 'derivative', 'determination', 'diagnostic', 'differentiation', 'dignified', 'diplomatic',
  'discrepancy', 'disintegration', 'disposal', 'distinctive', 'distortion', 'domestication', 'downplay', 'dramatic',
  'efficiency', 'elaborate', 'elimination', 'emancipation', 'emergence', 'emphasize', 'encounter', 'enhancement',
  'entrepreneurial', 'environmental', 'eradication', 'escalate', 'evaluation', 'exaggeration', 'expenditure', 'experiment',
  'exploration', 'fascination', 'feasibility', 'fluctuate', 'fragmentation', 'functionality', 'geographical', 'glamorize',
  'globalization', 'gratification', 'guarantee', 'harmonious', 'heritage', 'hierarchical', 'hospitality', 'humiliation',
  'hypothesis', 'identifiable', 'illustrative', 'immigration', 'impeccable', 'imperative', 'implementation', 'inadequate',
  'inauguration', 'incentivize', 'incompatibility', 'incorporate', 'indication', 'inevitable', 'influential', 'innovation',
  'instability', 'instructor', 'integrity', 'intellectual', 'intentional', 'intermediate', 'interpretation', 'intolerant',
  'invaluable', 'justification', 'legislation', 'liquidation', 'logical', 'magnificence', 'maintenance', 'manipulate',
  'marginalize', 'masterpiece', 'measurement', 'meditation', 'methodology', 'milestone', 'minimization', 'mobilization',
  'modification', 'monetary', 'motivation', 'multifaceted', 'narrative', 'negligence', 'noteworthy', 'nourishment',
  'objectivity', 'observation', 'optimistic', 'originate', 'outspoken', 'overcome', 'overestimate', 'oversee',
  'participation', 'perception', 'perfectionist', 'performance', 'perpetuate', 'phenomenon', 'philanthropy', 'philosophical',
  'physiological', 'pleasurable', 'polarization', 'politically', 'popularity', 'practicality', 'predictable', 'preference',
  'preliminary', 'preservation', 'prestigious', 'prevalence', 'principle', 'privatization', 'problematic', 'proclamation',
  'profound', 'progressive', 'projectile', 'proliferate', 'promotion', 'propaganda', 'prospective', 'protagonist',
  'psychological', 'qualification', 'questionable', 'radiation', 'rationality', 'reassurance', 'recognition', 'recreational',
  'redistribute', 'reflection', 'reformation', 'regeneration', 'regulation', 'rehabilitate', 'rejuvenate', 'reliable',
  'relinquish', 'remarkable', 'reminiscent', 'reparation', 'reproduction', 'requirement', 'reservation', 'resolution',
  'respectable', 'responsibility', 'restrictive', 'retrospective', 'revolutionary', 'rigorous', 'safeguard', 'sanctuary',
  'satisfaction', 'scientific', 'selfishness', 'sensitivity', 'significance', 'simplicity', 'simulation', 'sincerity',
  'solidarity', 'specialized', 'speculate', 'spontaneity', 'stabilization', 'standardize', 'strategic', 'subordination',
  'substantial', 'substitute', 'succession', 'sufficiency', 'superiority', 'supplementary', 'suppress', 'sustainability',
  'symbolic', 'synchronize', 'synergy', 'systematic', 'technicality', 'technological', 'tolerance', 'traditional', 'transformation', 'transparency', 'trepidation', 'turbulence', 'typicality', 'ultimatum', 'underestimate', 'unification',
  'uniqueness', 'universally', 'unpredictable', 'unquestionable', 'utilization', 'validity', 'variability', 'verification',
  'versatile', 'vibration', 'victorious', 'violation', 'visualization', 'volunteer', 'vulnerability', 'wholesomeness',
  'willingness', 'willingly', 'workforce', 'worthiness', 'worldwide', 'yielding', 'zealous', 'absorbent', 'accommodate',
  'accumulate', 'acknowledge', 'acquisition', 'adaptation', 'adjustable', 'administration', 'advocate', 'aggression',
  'allegiance', 'alleviate', 'ambitious', 'amusement', 'analysis', 'anniversary', 'appreciate', 'apprehensive', 'approval',
  'artificial', 'aspiration', 'assembly', 'assertive', 'assimilate', 'association', 'astonishing', 'atmosphere', 'attainable',
  'attractive', 'automation', 'availability', 'biography', 'brilliantly', 'broadcast', 'capacity', 'cautious', 'celebration',
  'challenge', 'charitable', 'circumstance', 'civilian', 'cohesive', 'collaborate', 'commence', 'commitment', 'commodity',
  'commute', 'compassion', 'competence', 'comprehensive', 'conceivable', 'consensus', 'conserve', 'considerate', 'consistent',
  'constantly', 'constructive', 'consume', 'contemplate', 'contentment', 'continuity', 'controversial', 'contribution',
  'cooperative', 'correspondence', 'credibility', 'criteria', 'crucial', 'cultivate', 'curiosity', 'customary', 'decline',
  'dedicated', 'deficiency', 'deliberate', 'demonstrate', 'denote', 'depression', 'derivative', 'detrimental', 'diligence',
  'diplomacy', 'disappointment', 'disaster', 'disclosure', 'discovery', 'discrimination', 'disposal', 'distinctive',
  'distribution', 'diversity', 'dominance', 'dynamic', 'economical', 'efficiency', 'elaborate', 'emphasize', 'endurance',
  'enterprise', 'enthusiasm', 'entitlement', 'entrance', 'equilibrium', 'equivalent', 'eradicate', 'essentially', 'evaluate',
  'evaporate', 'exaggerate', 'exclusion', 'expenditure', 'expensive', 'explicit', 'exploration', 'facilitate', 'fascinate',
  'favorable', 'feasible', 'fluctuation', 'fragmented', 'fundamentally', 'generalization', 'genetically', 'genuine',
  'globalize', 'gratify', 'grievance', 'guarantee', 'handicap', 'harmonize', 'hierarchy', 'hospitality', 'identification',
  'illegitimate', 'illustrate', 'imagination', 'imperfection', 'impractical', 'inadequate', 'incorporate', 'independence',
  'influential', 'infrastructure', 'innovation', 'insightful', 'instinctively', 'institution', 'instructor', 'insufficient',
  'intensity', 'interaction', 'interactive', 'interdependence', 'interference', 'intermediate', 'interpretation', 'interpretation', 'introspection', 'intuitive', 'invaluable', 'investment', 'invisible', 'irreplaceable', 'justifiable',
  'knowledgeable', 'legitimate', 'liberation', 'limitation', 'linguistic', 'livelihood', 'magnificent', 'mainstream',
  'manipulation', 'marketplace', 'meaningful', 'medication', 'meditation', 'metaphor', 'methodical', 'metropolitan',
  'militaristic', 'minimalist', 'miraculous', 'misconception', 'mobilization', 'modernize', 'modification', 'monumental',
  'morality', 'motivation', 'multifunctional', 'multipurpose', 'nationalism', 'naturalistic', 'negotiation', 'neutrality',
  'nostalgic', 'noteworthy', 'nutritional', 'observation', 'obsolescence', 'optimistic', 'organizational', 'orientation',
  'origination', 'overestimate', 'overlook', 'paradoxical', 'participation', 'perception', 'perfectionist', 'performance',
  'peripheral', 'permissible', 'perseverance', 'perspective', 'philanthropy', 'philosophical', 'physicality', 'pluralistic',
  'politically', 'polytechnic', 'popularity', 'positively', 'practitioner', 'predictability', 'preference', 'preliminary',
  'preservation', 'presumably', 'privatization', 'proclamation', 'profoundly', 'progressive', 'prohibitive', 'prominence',
  'proportionate', 'prospective', 'psychological', 'qualification', 'quantifiable', 'questionable', 'radiological', 'rationalize', 'realistically', 'reassurance', 'recognition', 'recreational', 'redistribution', 'reflection', 'reformation',
  'regenerative', 'rehabilitation', 'reincarnation', 'reiterate', 'relationship', 'relatively', 'remarkable', 'remembrance',
  'renovation', 'representation', 'reproduction', 'requirement', 'reservation', 'resilience', 'respectable', 'responsive',
  'restraining', 'restructure', 'revolutionize', 'rigorously', 'safeguard', 'satisfaction', 'scientifically', 'sensitivity',
  'significant', 'simplification', 'simulation', 'sophisticated', 'speculation', 'spontaneity', 'stabilization', 'standardize',
  'statistical', 'streamline', 'strengthen', 'subsequent', 'substantial', 'substitute', 'superiority', 'supportive',
  'suppressive', 'sustainability', 'symbolically', 'synchronization', 'systematically', 'technological', 'temperament',
  'theoretical', 'tolerance', 'traditional', 'transaction', 'transcendental', 'transformation', 'transparency', 'treacherous',
  'tremendous', 'troublesome', 'typicality', 'ultimate', 'unanimous', 'underestimate', 'underlying', 'undisputed', 'unification',
  'uniqueness', 'universalize', 'unpredictable', 'unquestionable', 'utilitarian', 'utilization', 'validation', 'variability',
  'verification', 'versatility', 'victorious', 'visualization', 'vocabulary', 'vulnerability', 'wholesomeness', 'willingness',
  'withstand', 'worldwide', 'worthwhile', 'youthfulness', 'zealousness', "abbreviation", "abolish", "absorption", "abundance", "accomplishment", "accountability", 
  "accusation", "adaptable", "adequacy", "adherence", "adjustment", "adoption", "advocate", 
  "aesthetic", "affiliation", "aggression", "allocation", "alteration", "ambiguity", "amplify", 
  "analytical", "anecdote", "anticipation", "applicable", "appraisal", "appropriation", 
  "arbitrary", "architectural", "artifact", "aspiration", "assessment", "assumption", 
  "attainment", "attribute", "authenticity", "autonomy", "availability", "background", 
  "bankruptcy", "barrier", "benchmark", "bias", "biography", "blend", "boast", "boundary", 
  "breakthrough", "bureaucracy", "calamity", "calculation", "capability", "capitalize", 
  "catastrophe", "celebrity", "certification", "chaotic", "clarification", "clientele", 
  "closure", "collaborate", "collapse", "commodity", "compassionate", "compel", "complication", 
  "comprehensive", "compromise", "concealment", "conceive", "concession", "concrete", 
  "condemn", "confer", "configuration", "conformity", "congregation", "conjunction", 
  "connotation", "conquer", "conscience", "conservative", "consistency", "consolidate", 
  "conspirator", "constituent", "constraint", "consultant", "contemplate", "continuity", 
  "contradiction", "controversy", "convenience", "conversion", "cooperate", "coordination", 
  "correlation", "correspondence", "credibility", "culminate", "cultivation", "cumulative", 
  "curtail", "debacle", "deception", "declaration", "dedication", "deficiency", "definition", 
  "delegation", "deliberate", "demanding", "demographic", "demonstrate", "denomination", 
  "depiction", "deprivation", "derivation", "desolate", "desperation", "detachment", 
  "devastation", "diagnosis", "dichotomy", "differentiation", "dignified", "diligence", 
  "diminish", "disastrous", "discreet", "discretion", "displacement", "disseminate", 
  "distinctive", "distortion", "diversify", "domination", "drastic", "duplication", 
  "dynamic", "eccentric", "economics", "efficiency", "elaborate", "elegance", "eligibility", 
  "eliminate", "eloquent", "embark", "embodiment", "emerge", "emphasis", "empirical", 
  "endorsement", "enforcement", "enhancement", "enrichment", "enthusiastic", "enumerate", 
  "environmental", "epidemic", "equilibrium", "eradication", "escalation", "essence", 
  "estimation", "ethnicity", "evacuate", "evaluation", "eventuality", "evolutionary", 
  "exaggeration", "exclusion", "execution", "exemplify", "exhaustive", "expansion", 
  "expectation", "expiration", "exploitation", "exquisite", "extension", "extravagant", 
  "facilitation", "fascination", "feasibility", "federal", "ferocious", "fertility", 
  "fluctuation", "foresight", "formulation", "foundation", "fraternity", "freelance", 
  "functionality", "fundamental", "generate", "generic", "generosity", "geographic", 
  "governance", "gratification", "gratitude", "groundwork", "guarantee", "guidance", 
  "harmonious", "harshness", "heritage", "hesitation", "hierarchy", "honorable", 
  "horizontal", "hospitality", "hypothetical", "identification", "ignorance", "illegitimate", 
  "illustration", "imminent", "immortality", "impartial", "imperative", "implementation", 
  "implicit", "impose", "impressive", "inadequacy", "incentive", "incidence", "inclusion", 
  "incorporate", "increment", "independence", "indication", "indigenous", "indispensable", 
  "inequality", "inevitable", "influential", "infrastructure", "ingenious", "initiation", 
  "innovation", "insightful", "insistence", "instinctive", "institutional", "integration", 
  "intellectual", "intensity", "intentional", "interact", "interference", "intermediate", 
  "intervention", "intimate", "intricate", "intriguing", "intuition", "investigate", 
  "ironic", "irregularity", "isolation", "jurisdiction", "justification", "kinship", 
  "laboratory", "lament", "landmark", "language", "legislation", "legitimacy", "liability", 
  "liberate", "licensing", "likelihood", "linguistic", "liquidation", "literary", 
  "livelihood", "loyalty", "luminescent", "magnificent", "maintenance", "majority", 
  "manifest", "manipulate", "marginal", "masterpiece", "materialistic", "mediation", 
  "meditation", "memorandum", "metaphor", "methodology", "meticulous", "migration", 
  "milestone", "minimalist", "miraculous", "mobilization", "moderation", "modification", 
  "monetary", "monopoly", "morality", "motivation", "multinational", "mutation", 
  "mysterious", "narrative", "nationalism", "necessitate", "negligence", "negotiation", 
  "network", "neutrality", "nomination", "nonexistent", "normative", "noteworthy", 
  "notification", "nourishment", "nullify", "obligation", "observation", "obstacle", 
  "obstructive", "obtainable", "occupation", "offensive", "openness", "optimal", 
  "optimization", "organization", "orientate", "originality", "overcome", "overlap", 
  "paradoxical", "parameter", "participant", "particularity", "partnership", "passionate", 
  "perception", "perfectionism", "performance", "permanent", "permissible", "perplex", 
  "perseverance", "persistence", "perspective", "philosopher", "philosophy", "placement", 
  "plethora", "polarization", "pollution", "population", "portrayal", "positivity", 
  "possessive", "potentially", "pragmatic", "precautionary", "precedent", "precisely", 
  "predecessor", "prediction", "predominant", "preference", "prejudice", "preliminary", 
  "preservation", "prestigious", "presumably", "pretension", "prevalence", "prevention", 
  "principality", "probability", "procedural", "proclamation", "proficiency", "progressive", 
  "projection", "prolific", "prominence", "promising", "promotion", "propaganda", 
  "propensity", "proportional", "proposition", "prospective", "prosperity", "protection", 
  "protocol", "prototype", "psychology", "publicity", "qualification", "quantitative", 
  "quarantine", "radical", "rational", "recession", "recipient", "recognition", "reconciliation", 
  "reconsider", "reconstruct", "recruitment", "refinement", "reflection", "reformation", 
  "regardless", "regression", "regulation", "rehabilitation", "reinforcement", "rejection", 
  "rejuvenate", "relatively", "reliability", "reluctant", "remorse", "remuneration", 
  "renewable", "reorganization", "representation", "repression", "resilience", "resonance", 
  "respective", "restoration", "restriction", "retaliation", "retrospective", "reveal", 
  "revenue", "revolution", "ridicule", "robust", "rotation", "routine", "safeguard", 
  "sanctuary", "saturation", "scenario", "sceptical", "scholarship", "scrutiny", "segmentation", 
  "selflessness", "sensational", "sensitivity", "sentimentality", "sequence", "significance", 
  "simulation", "skepticism", "sophistication", "specification", "speculation", "stability", 
  "stagnation", "standardization", "steadfast", "stimulus", "strategic", "streamline", 
  "subordinate", "subsidize", "substantial", "substitute", "subtlety", "sufficiency", 
  "supervision", "suppression", "sustainability", "symbolize", "synthesis", "systematic", 
  "tangible", "technological", "temporarily", "termination", "testimony", "theoretical", 
  "thorough", "tolerance", "traction", "transcend", "transformation", "transparency", 
  "tremendous", "tribulation", "triumphant", "ultimate", "unanticipated", "unconventional", 
  "underestimate", "undergo", "underlying", "underprivileged", "undertaking", "unequivocal", 
  "unification", "unpredictable", "unwilling", "uphold", "utilize", "validity", "variability", 
  "verification", "versatile", "vulnerability", "warehouse", "welfare", "widespread", 
  "withdrawal", "withstand", "workshop", "worship", "worthwhile", "wretchedness", "yearning", 
  "zealot", "zest"
];

export const FIXED_PHRASES_A1_A2 = [
"all set", "all done", "any idea?", "are we there yet?", "are you ready?", "as expected", 
  "as you wish", "at all times", "back and forth", "be careful", "be my guest", "be right back", 
  "better late than never", "better safe than sorry", "break a leg", "by all means", 
  "by chance", "by mistake", "by yourself", "call it a day", "can't complain", "check it out", 
  "cheer up", "close enough", "come on in", "coming right up", "count me in", "cut it out", 
  "deal with it", "do it yourself", "do me a favor", "don’t be late", "don’t worry", 
  "don’t mention it", "easy does it", "enough already", "excuse me", "fair enough", "fall apart", 
  "feel free", "few and far between", "figure it out", "fill me in", "find out", "for example", 
  "for instance", "for now", "for real", "for sure", "from scratch", "get going", "get lost", 
  "get off my back", "get over it", "get ready", "get well soon", "give me a break", 
  "give it a try", "go ahead", "go for it", "good luck", "good to know", "got it", 
  "great job", "guess what?", "hang in there", "hang on", "have a good day", "have a good night", 
  "have a nice day", "have a seat", "have fun", "help yourself", "here you go", "hold on", 
  "how about that", "how's it going?", "hurry up", "I apologize", "I believe so", 
  "I bet", "I can’t believe it", "I can’t stand it", "I can’t wait", "I don’t believe it", 
  "I don’t care", "I doubt it", "I feel the same", "I guess so", "I hope so", "I know right", 
  "I mean it", "I owe you one", "I see", "I suppose so", "I think so", "I was wondering", 
  "I wonder why", "if only", "in a bit", "in a hurry", "in advance", "in case", 
  "in charge", "in other words", "in progress", "in public", "in the meantime", 
  "in time", "it doesn’t matter", "it figures", "it happens", "it takes time", 
  "it’s all good", "it’s my turn", "it’s on me", "it’s over", "it’s the least I can do", 
  "it’s time", "just a moment", "just a sec", "just kidding", "just my luck", "just right", 
  "just so you know", "just the same", "keep going", "keep in touch", "keep it up", 
  "keep me posted", "keep out", "know what I mean?", "last but not least", "let it be", 
  "let it go", "let me know", "let’s go", "let’s see", "look alive", "look out", 
  "look who’s talking", "long story short", "lose your cool", "lost and found", "make a call", 
  "make a difference", "make it happen", "make it up", "make my day", "make sense", 
  "make sure", "maybe later", "me too", "more or less", "move on", "my pleasure", 
  "neat and tidy", "never better", "never mind", "nice going", "no big deal", "no harm done", 
  "no kidding", "no matter what", "no problem", "no thanks", "not again", "not a chance", 
  "not at all", "not bad", "not likely", "not much", "not really", "nothing to it", 
  "now or never", "of course", "on a roll", "on board", "on hold", "on my way", "on purpose", 
  "on second thought", "on the dot", "on time", "once in a while", "one moment please", 
  "only time will tell", "open your mind", "out of the blue", "over and out", "over there", 
  "pay attention", "pick up the pace", "piece of cake", "plain and simple", "pleased to meet you", 
  "point taken", "pretty much", "pull yourself together", "pushed for time", "put it off", 
  "put it together", "quite a few", "ready or not", "right away", "right on time", "say again?", 
  "see you around", "see you later", "see you soon", "settle down", "shake it off", 
  "show up", "sleep tight", "slow down", "so far so good", "so much for that", "speak up", 
  "stay calm", "stay tuned", "step by step", "stick with it", "still there?", "stop it", 
  "stop messing around", "suit yourself", "sure thing", "take a guess", "take a hike", 
  "take a look", "take care", "take it easy", "take note", "take your time", "talk later", 
  "tell me about it", "thank you", "thanks a bunch", "thanks anyway", "that figures", 
  "that’s enough", "that’s funny", "that’s right", "that’s that", "that’s true", "the last straw", 
  "the sooner the better", "things happen", "think about it", "think again", "think positive", 
  "time flies", "time to go", "to be honest", "to make matters worse", "too bad", "try again", 
  "try me", "under control", "under pressure", "understand?", "up to you", "use your head", 
  "wait for it", "wake up", "way to go", "we did it", "we’ll see", "what a relief", 
  "what about you?", "what a shame", "what can I say?", "what do you mean?", "what for?", 
  "what’s done is done", "what’s going on?", "what’s happening?", "what’s new?", 
  "what’s the plan?", "what’s up?", "when in doubt", "when pigs fly", "where are you?", 
  "where have you been?", "where were we?", "who knows?", "who’s there?", "why not?", 
  "with all due respect", "without a doubt", "words fail me", "work it out", "works for me", 
  "would you believe?", "yes please", "you are welcome", "you bet", "you did it", 
  "you know better", "you made it", "you name it", "you rock", "you said it", "you tell me", 
  "you’re almost there", "you’re on", "you’re right", "you’re the best", "you’re welcome", 
  "your call", "your turn", "zip it"
];

export const FIXED_PHRASES_A2_B2 = [
  "a bit of a stretch", "a blessing in disguise", "a breath of fresh air", "a piece of cake", 
  "a penny for your thoughts", "a touch of class", "a wild guess", "after all", "all of a sudden", 
  "all the best", "all the time", "as far as I know", "as good as it gets", "as it turns out", 
  "as much as possible", "at any rate", "at first sight", "at the end of the day", "at your service", 
  "back to square one", "behind closed doors", "best of luck", "between a rock and a hard place", 
  "bite the bullet", "break the ice", "bring it on", "by all means", "by the way", 
  "call it quits", "catch someone's eye", "catch up with", "clear the air", "come to an end", 
  "cool as a cucumber", "cross your fingers", "cut to the chase", "dawn of a new era", 
  "do your best", "don't beat around the bush", "don't hold your breath", "don't take it personally", 
  "easy come, easy go", "every now and then", "feel like a million bucks", "for the record", 
  "for what it's worth", "from the bottom of my heart", "give it a shot", "give me a hand", 
  "give me a break", "go back to the drawing board", "go for broke", "go out of your way", 
  "have a blast", "have a heart", "have a look", "have a point", "have a seat", 
  "have a word", "have an eye for", "have no idea", "have the guts", "hear it from someone", 
  "hit the books", "hit the road", "hold your horses", "in a nutshell", "in a pickle", 
  "in a tight spot", "in no time", "in the bag", "in the long run", "in the same boat", 
  "it’s about time", "it’s all in your head", "it’s not rocket science", "it’s your call", 
  "jump on the bandwagon", "just around the corner", "keep an eye on", "keep in mind", 
  "keep it to yourself", "keep on trying", "last but not least", "let's get started", 
  "let's make a deal", "like it or not", "look forward to", "look into it", 
  "lose track of time", "make a fuss", "make a joke", "make a long story short", 
  "make ends meet", "make up your mind", "miss the boat", "move heaven and earth", 
  "on cloud nine", "on good terms", "on the same page", "on the table", "once in a blue moon", 
  "out of control", "out of the question", "pay the price", "play it by ear", 
  "pull someone's leg", "put your feet up", "raise the bar", "read between the lines", 
  "roll with the punches", "run out of steam", "run the show", "see eye to eye", 
  "see how it goes", "see where this leads", "set the record straight", "shake hands", 
  "shoot the breeze", "speak of the devil", "spill the beans", "stand your ground", 
  "start from scratch", "step into someone’s shoes", "stick to the plan", "take a chance", 
  "take a deep breath", "take a hike", "take it easy", "take it with a grain of salt", 
  "the ball is in your court", "the best of both worlds", "the bottom line", 
  "the early bird catches the worm", "the sky's the limit", "the whole nine yards", 
  "throw in the towel", "to each their own", "treat someone like royalty", 
  "turn a blind eye", "turn up the heat", "up in the air", "wait and see", 
  "walk a mile in someone's shoes", "we'll cross that bridge when we come to it", 
  "what's the catch?", "when the chips are down", "work like a charm", 
  "you can count on me", "you can say that again", "you never know", 
  "your guess is as good as mine", "your time is up", "zip your lips", 
  "a change of heart", "a golden opportunity", "a hard pill to swallow", 
  "a new lease on life", "a real eye-opener", "a tough cookie", "a win-win situation", 
  "ahead of the curve", "all in all", "an arm and a leg", "back in the day", 
  "back to basics", "better half", "better late than never", "bite off more than you can chew", 
  "breathe easy", "bring something to the table", "bring your A-game", 
  "bump in the road", "burn the midnight oil", "call the shots", "cast in stone", 
  "change your tune", "clear as day", "come to terms", "cross that bridge when you get to it", 
  "cut corners", "don’t get carried away", "every little helps", "fall through the cracks", 
  "fingers crossed", "for crying out loud", "get in touch", "give the green light", 
  "go down in flames", "go out on a limb", "hit the jackpot", "keep the ball rolling", 
  "leave no stone unturned", "let the cat out of the bag", "make waves", "more often than not", 
  "mover and shaker", "off the beaten path", "once bitten, twice shy", "on the fence", 
  "play your cards right", "put all your eggs in one basket", "read the room", 
  "rock the boat", "see the big picture", "speak your mind", "stand up for", 
  "stick your neck out", "take a rain check", "that’s a wrap", "the elephant in the room", 
  "the last straw", "the odds are against you", "the whole kit and caboodle", 
  "throw a fit", "turn the tables", "under the weather", "up to no good", 
  "wait your turn", "what's your angle?", "write it down", "you live and learn", 
  "a different kettle of fish", "a fly in the ointment", "a match made in heaven", 
  "a recipe for disaster", "a tall order", "a thorn in my side", "as good as gold", 
  "as safe as houses", "as sweet as pie", "back to the drawing board", 
  "by the skin of your teeth", "get your act together", "hit the nail on the head", 
  "let the chips fall where they may", "more than meets the eye", "out of the frying pan", 
  "put your money where your mouth is", "speak with one voice", "the icing on the cake", 
  "the pen is mightier than the sword", "there's more than one way to skin a cat", 
  "to make a long story short", "to the bitter end", "when it rains, it pours", 
  "you can't judge a book by its cover"
];

export const FIXED_PHRASES_B2_C2 = [
  "a matter of opinion", "a necessary evil", "a storm in a teacup", "above and beyond", 
  "add fuel to the fire", "all things considered", "an open and shut case", "at a crossroads", 
  "at the drop of a hat", "at the end of the day", "at your fingertips", "back to the drawing board", 
  "be all and end all", "be on the same wavelength", "bear in mind", "beating around the bush", 
  "behind the scenes", "between a rock and a hard place", "bite the hand that feeds you", 
  "bite the bullet", "break new ground", "burning the midnight oil", "by the same token", 
  "call a spade a spade", "call it what it is", "catch someone off guard", "come to grips with", 
  "come to the fore", "cross that bridge when you come to it", "cut the mustard", 
  "dig your heels in", "do justice to", "draw the line", "each to their own", 
  "eat your words", "every cloud has a silver lining", "face the music", "fall into place", 
  "for better or worse", "for crying out loud", "for the sake of argument", "get a grip", 
  "get out of hand", "get something off your chest", "give someone a taste of their own medicine", 
  "go against the grain", "go down in history", "go out on a limb", "have your cake and eat it too", 
  "hold your horses", "hit the ground running", "hold someone accountable", "in a nutshell", 
  "in the long run", "in the same boat", "in the thick of it", "it’s high time", 
  "it’s not the end of the world", "it’s only a matter of time", "jump at the chance", 
  "keep your chin up", "kick the can down the road", "knock it out of the park", 
  "leave no stone unturned", "let bygones be bygones", "level the playing field", 
  "make a long story short", "make waves", "miss the boat", "more to the point", 
  "mountains out of molehills", "my hands are tied", "no time like the present", 
  "not a snowball's chance", "not for all the tea in China", "off the beaten path", 
  "on cloud nine", "on the back burner", "on the ball", "on the cutting edge", 
  "on the fence", "open a can of worms", "play it by ear", "pull yourself together", 
  "put all your eggs in one basket", "read the writing on the wall", 
  "run into a brick wall", "see eye to eye", "set the stage", "shoot yourself in the foot", 
  "spilling the beans", "step up your game", "sweep something under the rug", 
  "take a step back", "take it with a grain of salt", "take the bull by the horns", 
  "take the plunge", "the best of both worlds", "the calm before the storm", 
  "the devil is in the details", "the elephant in the room", "the end of the line", 
  "the icing on the cake", "the last straw", "the pot calling the kettle black", 
  "the proof is in the pudding", "the writing's on the wall", "there's no turning back", 
  "to be on the safe side", "to break the ice", "to each their own", "to go above and beyond", 
  "to make matters worse", "to put it mildly", "to the best of my knowledge", 
  "to the letter", "turn a blind eye", "turn the tide", "under the weather", 
  "up in the air", "wait for the dust to settle", "weigh your options", 
  "when all is said and done", "when it rains, it pours", "you can’t have your cake and eat it too", 
  "you can’t judge a book by its cover", "a double-edged sword", "a different kettle of fish", 
  "a tough nut to crack", "a wolf in sheep's clothing", "all bark and no bite", 
  "all in good time", "all roads lead to Rome", "all’s fair in love and war", 
  "an arm and a leg", "at a loss for words", "at face value", "at loggerheads", 
  "bite off more than you can chew", "blessing in disguise", "burn bridges", 
  "call someone out", "can’t see the forest for the trees", "catch someone red-handed", 
  "draw a blank", "eat someone’s lunch", "feel the pinch", "fighting an uphill battle", 
  "fly off the handle", "get a second wind", "get back on track", 
  "give someone the cold shoulder", "go down the rabbit hole", "go for broke", 
  "hit the nail on the head", "if the shoe fits, wear it", "in the heat of the moment", 
  "in the limelight", "jump through hoops", "keep your options open", 
  "kill two birds with one stone", "know the ropes", "lay your cards on the table", 
  "let sleeping dogs lie", "make a clean break", "make ends meet", 
  "money doesn't grow on trees", "no use crying over spilled milk", "not out of the woods", 
  "off the cuff", "on the right track", "on the same wavelength", "over the moon", 
  "paint the town red", "pay the piper", "put your foot down", "raise eyebrows", 
  "right off the bat", "run with the pack", "see through someone", 
  "sitting on the fence", "smell a rat", "spill the tea", "sweep the leg", 
  "take a leaf out of someone's book", "take it to heart", "the ball is in your court", 
  "the cream rises to the top", "the early bird gets the worm", "the grass is always greener", 
  "the hand that rocks the cradle", "the whole shebang", "there's no place like home", 
  "throw caution to the wind", "to bring to light", "to come full circle", 
  "to cut to the quick", "to feel under the weather", "to go out on a limb", 
  "to hold the fort", "to look the other way", "to take with a pinch of salt", 
  "turn the other cheek", "we’re all in the same boat", "what goes around comes around", 
  "what’s done is done", "when push comes to shove", "you can’t teach an old dog new tricks"
];

export const IDIOMS_A1_A2 = [
"a blessing in disguise", "a dime a dozen", "a piece of cake", "a taste of your own medicine", 
  "add fuel to the fire", "all ears", "all in the same boat", "at the drop of a hat", 
  "back to square one", "barking up the wrong tree", "beat around the bush", "between a rock and a hard place", 
  "bite the bullet", "break a leg", "break the ice", "bring home the bacon", 
  "burning the midnight oil", "bust someone's chops", "by the book", "call it a day", 
  "cast in stone", "catch someone off guard", "chicken out", "costs an arm and a leg", 
  "cross that bridge when you come to it", "cut corners", "cut to the chase", "don't count your chickens", 
  "don't cry over spilled milk", "don't put all your eggs in one basket", "down in the dumps", 
  "driving me up the wall", "easy as pie", "feel under the weather", "fish out of water", 
  "flash in the pan", "for crying out loud", "give someone a hand", "give the cold shoulder", 
  "go for broke", "go out on a limb", "have a heart", "have it your way", 
  "have the last laugh", "hit the nail on the head", "hit the sack", "in a pickle", 
  "in hot water", "it takes two to tango", "keep your chin up", "kill two birds with one stone", 
  "let the cat out of the bag", "make a mountain out of a molehill", "miss the boat", 
  "not playing with a full deck", "off the beaten path", "on cloud nine", "once in a blue moon", 
  "out of the blue", "piece of cake", "pull someone's leg", "put all your eggs in one basket", 
  "put your best foot forward", "put your foot in your mouth", "read between the lines", 
  "red herring", "sitting on the fence", "spill the beans", "spilling the tea", 
  "take it with a grain of salt", "the ball is in your court", "the best of both worlds", 
  "the early bird catches the worm", "the elephant in the room", "the whole nine yards", 
  "there's no place like home", "throw in the towel", "to be on the safe side", 
  "to get cold feet", "to make ends meet", "to run out of steam", "to see eye to eye", 
  "turn a blind eye", "under the weather", "when it rains, it pours", "you can count on me", 
  "you can't have your cake and eat it too", "you can't teach an old dog new tricks", 
  "a breath of fresh air", "a change of heart", "a drop in the bucket", "a fair shake", 
  "a foot in the door", "a shot in the dark", "a taste of the good life", "all that glitters is not gold", 
  "as easy as pie", "as good as gold", "as luck would have it", "at the end of the day", 
  "back to basics", "barking up the wrong tree", "beat a dead horse", "break the bank", 
  "bring up the rear", "burn the midnight oil", "by the skin of your teeth", 
  "call someone's bluff", "catch someone off guard", "chomping at the bit", 
  "come hell or high water", "cut the mustard", "devil's advocate", 
  "don't beat around the bush", "don't judge a book by its cover", 
  "driven to distraction", "easy come, easy go", "falling on deaf ears", 
  "feather in your cap", "find your feet", "fish out of water", 
  "flying off the handle", "fools rush in", "from the horse's mouth", 
  "full of hot air", "get a second wind", "get your act together", 
  "go down in flames", "go the extra mile", "hit the books", 
  "in a nutshell", "in the bag", "in the loop", "in the same boat", 
  "jump on the bandwagon", "keep your nose clean", "let the chips fall where they may", 
  "like a kid in a candy store", "make a long story short", "mind your own business", 
  "miss the mark", "more than meets the eye", "not my cup of tea", 
  "off the top of my head", "on the same page", "one in a million", 
  "pay the piper", "play it by ear", "pull the wool over someone's eyes", 
  "put the cart before the horse", "rain on someone's parade", "rock the boat", 
  "roll with the punches", "run of the mill", "see how the land lies", 
  "see the writing on the wall", "shoot from the hip", "sleep on it", 
  "sweeping under the rug", "take a rain check", "take it easy", 
  "the best of intentions", "the last straw", "the odds are against you", 
  "the proof is in the pudding", "the tip of the iceberg", "there's no such thing as a free lunch", 
  "to bite the hand that feeds you", "to break the mold", "to bring to light", 
  "to face the music", "to pull yourself together", "to rain on someone's parade", 
  "to sweep under the rug", "to throw caution to the wind", "under your nose", 
  "walk a mile in someone's shoes", "watch your back", "when push comes to shove", 
  "you can’t judge a book by its cover", "a hard pill to swallow", "a match made in heaven", 
  "a slap on the wrist", "an arm and a leg", "at your fingertips", 
  "bark up the wrong tree", "be on thin ice", "bigger fish to fry", 
  "blow off steam", "call the shots", "change of heart", "climbing the walls", 
  "come to terms with", "cutting corners", "digging your heels in", 
  "draw the line", "drop the ball", "feeling blue", "fit as a fiddle", 
  "go for broke", "keep your head above water", "last but not least", 
  "leave high and dry", "light at the end of the tunnel", "like pulling teeth", 
  "long story short", "make your day", "nipped in the bud", 
  "on the fence", "on thin ice", "once bitten, twice shy", 
  "pulling your leg", "putting the cart before the horse", "reading the riot act", 
  "raining cats and dogs", "saved by the bell", "short end of the stick", 
  "sitting pretty", "skeletons in the closet", "spill your guts", 
  "taking a stab at", "the ballpark figure", "the elephant in the room", 
  "the whole kit and caboodle", "there's more than one way to skin a cat", 
  "to go against the grain", "to hear it straight from the horse's mouth", 
  "to hit the ground running", "to keep your chin up", "to let sleeping dogs lie", 
  "to make a mountain out of a molehill", "to pay lip service", "to play devil's advocate", 
  "to take something with a grain of salt", "to throw in the towel", "turning a blind eye", 
  "under the weather", "when all is said and done", "you can't make an omelet without breaking eggs", 
  "a dime a dozen", "a taste of your own medicine", "all in good time", 
  "beating a dead horse", "catch someone off guard", "draw a blank", 
  "easy as pie", "feeling under the weather", "for better or worse", 
  "in a jam", "keep your options open", "let your hair down", 
  "more than meets the eye", "no pain, no gain", "not the end of the world", 
  "on the fence", "over the moon", "piece of cake", "put your best foot forward", 
  "read between the lines", "ring a bell", "sitting on the fence", 
  "take it with a grain of salt", "the best of both worlds", "the tip of the iceberg", 
  "to make a long story short", "under the weather", "when the going gets tough"
];

export const IDIOMS_A2_B2 = [
  "a breath of fresh air", "a picture is worth a thousand words", "a piece of the action", 
  "a snowball effect", "all in the same boat", "as easy as pie", "as fresh as a daisy", 
  "at the end of the day", "back to the drawing board", "barking up the wrong tree", 
  "beating around the bush", "between a rock and a hard place", "bite the bullet", 
  "blessing in disguise", "break the ice", "bring something to the table", 
  "burning the midnight oil", "by the skin of your teeth", "call it a day", 
  "catch someone off guard", "chicken out", "come rain or shine", "cost an arm and a leg", 
  "cross that bridge when you come to it", "cut corners", "cut to the chase", 
  "don't count your chickens before they hatch", "don't cry over spilled milk", 
  "don't put all your eggs in one basket", "down to earth", "easy come, easy go", 
  "feather in your cap", "feel under the weather", "fish out of water", 
  "for crying out loud", "give someone the cold shoulder", "go for broke", 
  "go out on a limb", "have a heart", "have the upper hand", "hit the nail on the head", 
  "in a pickle", "in the bag", "it's a small world", "keep your chin up", 
  "know the ropes", "let the cat out of the bag", "make a long story short", 
  "miss the boat", "no pain, no gain", "off the beaten path", "on cloud nine", 
  "once in a blue moon", "out of the blue", "piece of cake", "pull someone's leg", 
  "put all your eggs in one basket", "put your best foot forward", "read between the lines", 
  "spill the beans", "take it with a grain of salt", "the ball is in your court", 
  "the best of both worlds", "the cream rises to the top", "the early bird catches the worm", 
  "the elephant in the room", "the whole nine yards", "throw in the towel", 
  "to be in hot water", "to bite the bullet", "to break the ice", 
  "to burn the midnight oil", "to cut to the chase", "to get cold feet", 
  "to hit the hay", "to keep your fingers crossed", "to let sleeping dogs lie", 
  "to make ends meet", "to miss the boat", "to pull someone's leg", 
  "to see eye to eye", "to take it easy", "to take with a grain of salt", 
  "to throw caution to the wind", "under the weather", "when it rains, it pours", 
  "you can’t have your cake and eat it too", "you can't judge a book by its cover", 
  "a hard pill to swallow", "a match made in heaven", "a piece of cake", 
  "a snowball effect", "a taste of your own medicine", "after the fact", 
  "all ears", "all thumbs", "back to square one", "bite off more than you can chew", 
  "break the bank", "bring down the house", "broke the ice", "burn the midnight oil", 
  "call someone's bluff", "cut the mustard", "devil's advocate", 
  "don't beat around the bush", "draw the line", "drive someone up the wall", 
  "eat like a bird", "elephant in the room", "every cloud has a silver lining", 
  "fall on deaf ears", "for the time being", "give someone a hand", 
  "go down in flames", "have a chip on your shoulder", "have your head in the clouds", 
  "hit the books", "in a nutshell", "in the loop", "in the same boat", 
  "jump on the bandwagon", "keep your eyes peeled", "let bygones be bygones", 
  "make a mountain out of a molehill", "not my cup of tea", "off the hook", 
  "on the same page", "put your foot down", "rain on someone's parade", 
  "read the room", "see eye to eye", "skeletons in the closet", 
  "sitting on the fence", "spill the tea", "the best of both worlds", 
  "the bottom line", "the cat's out of the bag", "the icing on the cake", 
  "to burn bridges", "to face the music", "to give someone the runaround", 
  "to get a second wind", "to hit the ground running", "to keep your chin up", 
  "to land on your feet", "to let the cat out of the bag", "to pull yourself together", 
  "to put all your eggs in one basket", "to put your best foot forward", 
  "to see the bigger picture", "to throw in the towel", "walk a mile in someone’s shoes", 
  "when push comes to shove", "you can’t teach an old dog new tricks", 
  "a dime a dozen", "a good deal", "a leopard can't change its spots", 
  "a snowball effect", "a wolf in sheep's clothing", "all in good time", 
  "at the drop of a hat", "back to the drawing board", "burning the midnight oil", 
  "catch 22", "come rain or shine", "cross that bridge when you come to it", 
  "don't bite the hand that feeds you", "don't put all your eggs in one basket", 
  "drive someone up the wall", "easier said than done", "fit as a fiddle", 
  "fools rush in", "get a grip", "get off on the wrong foot", 
  "give someone a run for their money", "go against the grain", 
  "have your head in the clouds", "hit the nail on the head", "hold your horses", 
  "in the bag", "jump through hoops", "kick the bucket", "know the ropes", 
  "let your hair down", "long story short", "make a long story short", 
  "more than meets the eye", "not playing with a full deck", "once bitten, twice shy", 
  "pay the piper", "put the cart before the horse", "read between the lines", 
  "run of the mill", "saved by the bell", "skeletons in the closet", 
  "take it with a pinch of salt", "the ball is in your court", 
  "the whole shebang", "to be on the safe side", "to get your act together", 
  "to hit the nail on the head", "to keep your chin up", 
  "to let the chips fall where they may", "to make a long story short", 
  "to run out of steam", "to see eye to eye", "under the weather", 
  "when the chips are down", "you can't have your cake and eat it too", 
  "a blessing in disguise", "a little bird told me", "a stone's throw away", 
  "all bark and no bite", "as fit as a fiddle", "as good as gold", 
  "at sixes and sevens", "at the eleventh hour", "back to square one", 
  "barking up the wrong tree", "be careful what you wish for", 
  "better late than never", "between a rock and a hard place", 
  "bring something to the table", "burn the midnight oil", "call it a night", 
  "chasing rainbows", "climbing the walls", "come what may", "cut to the quick", 
  "devil is in the details", "don't judge a book by its cover", "drive someone crazy", 
  "every cloud has a silver lining", "feel the pinch", "fit as a fiddle", 
  "fly off the handle", "go down in history", "go for broke", 
  "have a chip on your shoulder", "have a heart of gold", 
  "hit the ground running", "in the driver's seat", "keep your fingers crossed", 
  "let sleeping dogs lie", "light at the end of the tunnel", 
  "long story short", "make a clean break", "no time like the present", 
  "off the beaten track", "on the ball", "on the fence", "out of the frying pan", 
  "over the moon", "rain on your parade", "read the fine print", 
  "run out of luck", "saved by the bell", "see the bigger picture", 
  "show your true colors", "the ball is in your court", 
  "the calm before the storm", "the elephant in the room", 
  "the icing on the cake", "the last straw", "the light at the end of the tunnel", 
  "to cut the mustard", "to go against the grain", "to have a heart", 
  "to keep your head above water", "to pull someone's leg", "to turn a blind eye", 
  "under the radar", "when pigs fly", "you can't take it with you", 
  "a change of pace", "a fair shake", "a fish out of water", 
  "a red herring", "a tall order", "a wild goose chase", 
  "all in all", "all in good time", "as fresh as a daisy", 
  "as right as rain", "back against the wall", "beat the heat", 
  "call the kettle black", "can't hold a candle to", "catch someone red-handed", 
  "climbing the walls", "cross your fingers", "cut out for", 
  "don't throw the baby out with the bathwater", "elephant in the room", 
  "every dog has its day", "feather your nest", "from rags to riches", 
  "get your act together", "give the green light", "go against the flow", 
  "have the last laugh", "hit the hay", "in the same ballpark", 
  "keep your options open", "let the cat out of the bag", 
  "make a mountain out of a molehill", "meet someone halfway", 
  "not worth a hill of beans", "on the same wavelength", 
  "put your foot in your mouth", "rain cats and dogs", 
  "see the light", "shoot for the stars", "sleep like a baby", 
  "take the plunge", "the ballpark figure", "the last nail in the coffin", 
  "to bite the bullet", "to break new ground", "to burn the midnight oil", 
  "to come to terms with", "to cry over spilled milk", "to get the ball rolling", 
  "to hit the jackpot", "to know the ropes", "to learn the ropes", 
  "to pull yourself together", "to sell like hotcakes", 
  "to shoot the breeze", "to throw in the towel", "to walk on eggshells", 
  "under your nose", "when the chips are down", "you can't win them all"
];

export const IDIOMS_B2_C2 = [
  "a bitter pill to swallow", "a blessing in disguise", "a dime a dozen", 
  "a flash in the pan", "a fool's paradise", "a horse of a different color", 
  "a leopard can't change its spots", "a needle in a haystack", "a red herring", 
  "a safe bet", "a tall order", "a taste of your own medicine", 
  "a thorn in someone's side", "a wolf in sheep's clothing", "all bark and no bite", 
  "all dressed up and nowhere to go", "all hat and no cattle", 
  "all talk and no action", "as clear as mud", "as fit as a fiddle", 
  "as good as it gets", "as right as rain", "back to the drawing board", 
  "barking up the wrong tree", "beating a dead horse", "bite the bullet", 
  "bite the hand that feeds you", "burning the midnight oil", "call the shots", 
  "cat's out of the bag", "change of heart", "chasing shadows", 
  "close but no cigar", "cold feet", "cross that bridge when you come to it", 
  "cut to the chase", "cutting corners", "devil's advocate", 
  "down to the wire", "drawing a blank", "dressed to the nines", 
  "elephant in the room", "every cloud has a silver lining", 
  "face the music", "feather your nest", "fire in the belly", 
  "flying off the handle", "for the sake of argument", 
  "get a second wind", "get cold feet", "get your ducks in a row", 
  "give someone the benefit of the doubt", "give the green light", 
  "go against the grain", "go out on a limb", "go the extra mile", 
  "hand in glove", "have a chip on your shoulder", "have a field day", 
  "have your cake and eat it too", "hit the ground running", 
  "in a nutshell", "in the heat of the moment", "in the long run", 
  "in the same boat", "it takes two to tango", "jump through hoops", 
  "keep your chin up", "kick the bucket", "kill two birds with one stone", 
  "knock on wood", "know the ropes", "last straw", "leave no stone unturned", 
  "let sleeping dogs lie", "light at the end of the tunnel", 
  "make a mountain out of a molehill", "miss the boat", 
  "no stone unturned", "not a spark of decency", "on thin ice", 
  "on the ball", "on the fence", "out of the loop", 
  "par for the course", "pay the piper", "play it by ear", 
  "play with fire", "pull the rug out from under someone", 
  "put all your eggs in one basket", "put your cards on the table", 
  "put your foot down", "rain on someone's parade", "read between the lines", 
  "red tape", "run out of steam", "saved by the bell", 
  "skeletons in the closet", "slip through the cracks", 
  "spill the beans", "spill the tea", "the ball is in your court", 
  "the best of both worlds", "the calm before the storm", 
  "the elephant in the room", "the grass is always greener", 
  "the icing on the cake", "the last straw", "the whole nine yards", 
  "to add fuel to the fire", "to break the mold", "to bury the hatchet", 
  "to change the tune", "to cross that bridge when you come to it", 
  "to draw the line", "to get the ball rolling", "to hit the nail on the head", 
  "to keep your cards close to your chest", "to let the cat out of the bag", 
  "to make ends meet", "to pay lip service", "to read the riot act", 
  "to run the show", "to sit on the fence", "to sleep on it", 
  "to take it with a grain of salt", "to throw in the towel", 
  "to turn a blind eye", "to wash your hands of something", 
  "to wear your heart on your sleeve", "to wind up", 
  "under the weather", "when it rains, it pours", "you can't have your cake and eat it too", 
  "a bitter pill to swallow", "a red letter day", "a stitch in time saves nine", 
  "a tough nut to crack", "actions speak louder than words", 
  "as cool as a cucumber", "as old as the hills", "back to the salt mines", 
  "barking up the wrong tree", "beating a dead horse", "better late than never", 
  "bite the dust", "break the bank", "bring to the table", 
  "burn the candle at both ends", "by the book", "call it a night", 
  "climbing the walls", "come what may", "cut and dried", 
  "cut to the quick", "devil is in the details", "don’t bite off more than you can chew", 
  "don't judge a book by its cover", "draw a line in the sand", 
  "easy does it", "feather in your cap", "fit as a fiddle", 
  "give someone a run for their money", "go down in flames", 
  "have a heart", "hit the jackpot", "in a pickle", 
  "keep your fingers crossed", "know the score", "leave someone hanging", 
  "make a name for yourself", "more than meets the eye", 
  "mutton dressed as lamb", "not playing with a full deck", 
  "off the beaten path", "on the tip of your tongue", 
  "play the field", "pull someone's leg", "red flag", 
  "see eye to eye", "skeletons in the closet", 
  "spilling the beans", "take with a grain of salt", 
  "the ball is in your court", "the best of both worlds", 
  "the elephant in the room", "to break the ice", 
  "to face the music", "to get a foot in the door", 
  "to give someone the cold shoulder", "to go for broke", 
  "to hit the hay", "to keep your head above water", 
  "to let the cat out of the bag", "to pull yourself together", 
  "to put your best foot forward", "to see the light", 
  "to throw caution to the wind", "to turn over a new leaf", 
  "to walk a tightrope", "under the radar", "when push comes to shove", 
  "you can’t teach an old dog new tricks", "a breath of fresh air", 
  "a house of cards", "a laugh a minute", "a match made in heaven", 
  "a penny for your thoughts", "a picture paints a thousand words", 
  "a problem shared is a problem halved", "a shot in the arm", 
  "all of a sudden", "as easy as pie", "as the crow flies", 
  "back against the wall", "behind closed doors", "between a rock and a hard place", 
  "big fish in a small pond", "bite the bullet", "burning the midnight oil", 
  "call someone's bluff", "chasing rainbows", "cherry on the cake", 
  "come out of the woodwork", "count your blessings", 
  "cut corners", "devil's advocate", "don't count your chickens", 
  "every little bit helps", "feel the pinch", "find your feet", 
  "fit as a fiddle", "fools rush in where angels fear to tread", 
  "for crying out loud", "give the cold shoulder", "go against the grain", 
  "have a change of heart", "hit the nail on the head", 
  "in the line of fire", "jumping on the bandwagon", "keep your chin up", 
  "let it slide", "light at the end of the tunnel", 
  "long story short", "make a clean breast of it", 
  "miss the mark", "not cut out for it", "off the beaten track", 
  "on the same page", "open Pandora's box", "paint the town red", 
  "put your foot in it", "read the fine print", "see the writing on the wall", 
  "sitting on the fence", "the early bird catches the worm", 
  "the heart of the matter", "to cut the mustard", 
  "to get the short end of the stick", "to have a heart of gold", 
  "to keep someone at arm's length", "to let someone down", 
  "to make a mountain out of a molehill", "to put your foot down", 
  "to spill the beans", "to take a back seat", "to take something with a pinch of salt", 
  "under the weather", "when the chips are down", 
  "you can’t have it both ways"
];